### ISSUE TITLE
question for datasets

### ISSUE THREAD

**Issue by Hanminghao** [shaoweinuaa/Code-for-paper-in-TMI2023#1]
Dear Professor Shao,

I hope this message finds you well. I would like to express my sincere appreciation for your outstanding work. I have a few queries regarding the file formats of RNAseq.xlsx and miRNAseq.xlsx mentioned in the code. Additionally, I am curious to know if the data was obtained from TCGA or cBioPortal. If it is not too much trouble, would it be possible for you to share the files with me?  I look forward to your response.

Thank you very much.

**Comment by shaoweinuaa** [comment]
Thanks for pointing it out, and we have uploaded the missing files.  All the image and genomic data are public avaiable at TCGA.

**Comment by Hanminghao** [comment]
Got it! Thanks!
